export const PARTIES = [
  { 
    id: "NPA", 
    name: "Nouveau Parti Anticapitaliste", 
    orientation: "Extrême gauche", 
    personality: "Philippe Poutou, Olivier Besancenot",
    personalityPhotos: ["/images/personnalites/philippe-poutou.jpg", "/images/personnalites/olivier-besancenot.jpg"],
    description: "Votre positionnement est en faveur de changements radicaux de la société.",
    logo: { light: "/images/logospartis/light/NPA.png", dark: "/images/logospartis/dark/NPA.png" },
    color: { light: '#a90000', dark: '#a90000' },
    compass: { x: -90, y: -90 },
    radicalism: 0.97,
    cohesion: 0.85
  },
  { 
    id: "LO", 
    name: "Lutte Ouvrière", 
    orientation: "Extrême gauche", 
    personality: "Nathalie Arthaud",
    personalityPhotos: ["/images/personnalites/nathalie-arthaud.jpg"],
    description: "Votre projet de société est basé sur le communisme révolutionnaire et la défense des intérêts des travailleurs contre le capital.",
    logo: { light: "/images/logospartis/light/LO.png", dark: "/images/logospartis/dark/LO.png" },
    color: { light: '#a90000', dark: '#a90000' },
    compass: { x: -100, y: -80 },
    radicalism: 0.95,
    cohesion: 0.98
  },
  { 
    id: "LFI", 
    name: "La France Insoumise", 
    orientation: "Extrême gauche", 
    personality: "Jean-Luc Mélenchon, Mathilde Panot",
    personalityPhotos: ["/images/personnalites/jean-luc-melenchon.jpg", "/images/personnalites/mathilde-panot.jpg"],
    description: "Votre positionnement est en faveur de changements radicaux de la société pour plus de justice et d'égalité.",
    logo: { light: "/images/logospartis/light/LFI.png", dark: "/images/logospartis/dark/LFI.png" },
    color: { light: '#e10000', dark: '#e10000' },
    compass: { x: -80, y: -70 },
    radicalism: 0.85,
    cohesion: 0.90
  },
   { 
    id: "PCF", 
    name: "Parti Communiste Français", 
    orientation: "Communiste", 
    personality: "Fabien Roussel",
    personalityPhotos: ["/images/personnalites/fabien-roussel.jpg"],
    description: "Votre positionnement est en faveur des droits des travailleurs, de l'intervention de l'État dans l'économie et des services publics.",
    logo: { light: "/images/logospartis/light/PCF.png", dark: "/images/logospartis/dark/PCF.png" },
    color: { light: '#f60000', dark: '#f60000' },
    compass: { x: -75, y: 20 },
    radicalism: 0.60,
    cohesion: 0.70
  },
  { 
    id: "Générations", 
    name: "Générations", 
    orientation: "Gauche", 
    personality: "Benoît Hamon",
    personalityPhotos: ["/images/personnalites/benoit-hamon.jpg"],
    description: "Votre programme se concentre sur l'écologie, la justice sociale et une démocratie participative.",
    logo: { light: "/images/logospartis/light/Generations.png", dark: "/images/logospartis/dark/Generations.png" },
    color: { light: '#f6004a', dark: '#f6004a' },
    compass: { x: -60, y: -60 },
    radicalism: 0.70,
    cohesion: 0.60
  },
  { 
    id: "PS", 
    name: "Parti Socialiste", 
    orientation: "Gauche", 
    personality: "Olivier Faure, Anne Hidalgo, François Hollande, Raphaël Glucksmann",
    personalityPhotos: ["/images/personnalites/olivier-faure.jpg", "/images/personnalites/anne-hidalgo.jpg", "/images/personnalites/francois-hollande.jpg", "/images/personnalites/raphael-glucksmann.jpg"],
    description: "Vous croyez en un État-providence fort qui régule l'économie tout en défendant les libertés individuelles.",
    logo: { light: "/images/logospartis/light/PS.png", dark: "/images/logospartis/dark/PS.png" },
    color: { light: '#f60085', dark: '#f60085' },
    compass: { x: -40, y: -30 },
    radicalism: 0.35,
    cohesion: 0.40
  },
  { 
    id: "EELV", 
    name: "Les Écologistes", 
    orientation: "Gauche écologiste", 
    personality: "Marine Tondelier, Sandrine Rousseau, Yannick Jadot",
    personalityPhotos: ["/images/personnalites/marine-tondelier.jpg", "/images/personnalites/sandrine-rousseau.jpg", "/images/personnalites/yannick-jadot.jpg"],
    description: "L'écologie est au cœur de vos préoccupations, guidant vos choix économiques et sociaux.",
    logo: { light: "/images/logospartis/light/EELV.png", dark: "/images/logospartis/dark/EELV.png" },
    color: { light: '#12B850', dark: '#12B850' },
    compass: { x: -60, y: -70 },
    radicalism: 0.70,
    cohesion: 0.50
  },
    { 
    id: "PRG", 
    name: "Parti Radical de Gauche", 
    orientation: "Centre gauche", 
    personality: "Guillaume Lacroix",
    personalityPhotos: ["/images/personnalites/guillaume-lacroix.jpg"],
    description: "Vous défendez un libéralisme social, où l'économie de marché est tempérée par des politiques de justice sociale.",
    logo: { light: "/images/logospartis/light/PRG.png", dark: "/images/logospartis/dark/PRG.png" },
    color: { light: '#e200f6', dark: '#e200f6' },
    compass: { x: -20, y: -40 },
    radicalism: 0.25,
    cohesion: 0.65
  },
  { 
    id: "Modem", 
    name: "Mouvement Démocrate", 
    orientation: "Centre", 
    personality: "François Bayrou",
    personalityPhotos: ["/images/personnalites/francois-bayrou.jpg"],
    description: "Vous défendez des valeurs centristes et européennes, en faveur d'une économie sociale de marché et de la modernisation de la vie politique.",
    logo: { light: "/images/logospartis/light/Modem.png", dark: "/images/logospartis/dark/Modem.png" },
    color: { light: '#E87109', dark: '#E87109' },
    compass: { x: 20, y: -20 },
    radicalism: 0.20,
    cohesion: 0.75
  },
   { 
    id: "Renaissance", 
    name: "Renaissance", 
    orientation: "Centre", 
    personality: "Emmanuel Macron, Gabriel Attal",
    personalityPhotos: ["/images/personnalites/emmanuel-macron.jpg", "/images/personnalites/gabriel-attal.jpg"],
    description: "Vos réponses montrent un équilibre entre différentes sensibilités, en faveur d'un État réformateur et pragmatique.",
    logo: { light: "/images/logospartis/light/Renaissance.png", dark: "/images/logospartis/dark/Renaissance.png" },
    color: { light: '#F2DD35', dark: '#F2DD35' },
    compass: { x: 30, y: 30 },
    radicalism: 0.40,
    cohesion: 0.50
  },
  { 
    id: "Horizons", 
    name: "Horizons", 
    orientation: "Centre droit", 
    personality: "Édouard Philippe",
    personalityPhotos: ["/images/personnalites/edouard-philippe.jpg"],
    description: "Vous êtes en faveur du libre marché et de moins d'intervention de l'État, avec une certaine fermeté sur la sécurité.",
    logo: { light: "/images/logospartis/light/Horizons.png", dark: "/images/logospartis/dark/Horizons.png" },
    color: { light: '#0CABCF', dark: '#0CABCF' },
    compass: { x: 40, y: 40 },
    radicalism: 0.50,
    cohesion: 0.70
  },
  {
    id: "UDI",
    name: "Union des Démocrates et Indépendants",
    orientation: "Centre droit",
    personality: "Jean-Louis Borloo",
    personalityPhotos: ["/images/personnalites/jean-louis-borloo.jpg"],
    description: "Vous êtes en faveur d'une Europe forte, d'un libéralisme social et d'une approche réformatrice de la politique.",
    logo: { light: "/images/logospartis/light/UDI.png", dark: "/images/logospartis/dark/UDI.png" },
    color: { light: '#A410DE', dark: '#A410DE' },
    compass: { x: 40, y: -10 },
    radicalism: 0.35,
    cohesion: 0.55
  },
    { 
    id: "LR", 
    name: "Les Républicains", 
    orientation: "Droite", 
    personality: "Laurent Wauquiez, Bruno Retailleau, Valérie Pécresse",
    personalityPhotos: ["/images/personnalites/laurent-wauquiez.jpg", "/images/personnalites/bruno-retailleau.jpg", "/images/personnalites/valerie-precresse.jpg"],
    description: "Vous défendez une approche libérale de l'économie et êtes attaché(e) aux valeurs conservatrices et à l'autorité.",
    logo: { light: "/images/logospartis/light/LR.png", dark: "/images/logospartis/dark/LR.png" },
    color: { light: '#222BC7', dark: '#222BC7' },
    compass: { x: 60, y: 60 },
    radicalism: 0.60,
    cohesion: 0.50
  },
  { 
    id: "UDR", 
    name: "Union de la Droite pour la République", 
    orientation: "Droite nationaliste", 
    personality: "Éric Ciotti",
    personalityPhotos: ["/images/personnalites/eric-ciotti.jpg"],
    description: "Vous défendez une approche de droite classique, axée sur la souveraineté, l'ordre et la baisse des impôts.",
    logo: { light: "/images/logospartis/light/UDR.png", dark: "/images/logospartis/dark/UDR.png" },
    color: { light: '#2A48B5', dark: '#2A48B5' },
    compass: { x: 70, y: 75 },
    radicalism: 0.75,
    cohesion: 0.90
  },
  { 
    id: "RN", 
    name: "Rassemblement National", 
    orientation: "Droite nationaliste", 
    personality: "Jordan Bardella, Marine Le Pen",
    personalityPhotos: ["/images/personnalites/jordan-bardella.jpg", "/images/personnalites/marine-le-pen.jpg"],
    description: "Vos priorités sont la souveraineté nationale, le contrôle des frontières et le renforcement de l'ordre.",
    logo: { light: "/images/logospartis/light/RN.png", dark: "/images/logospartis/dark/RN.png" },
    color: { light: '#0629A1', dark: '#0629A1' },
    compass: { x: -30, y: 85 },
    radicalism: 0.65,
    cohesion: 0.85
  },
  { 
    id: "Debout la France", 
    name: "Debout la France", 
    orientation: "Droite souverainiste", 
    personality: "Nicolas Dupont-Aignan",
    personalityPhotos: ["/images/personnalites/nicolas-dupont-aignan.jpg"],
    description: "Vous défendez la souveraineté de la France et un État qui protège son économie, ses valeurs et ses frontières.",
    logo: { light: "/images/logospartis/light/DLF.png", dark: "/images/logospartis/dark/DLF.png" },
    color: { light: '#1d09ff', dark: '#1d09ff' },
    compass: { x: 50, y: 80 },
    radicalism: 0.80,
    cohesion: 0.90
  },
  { 
    id: "Reconquête", 
    name: "Reconquête", 
    orientation: "Extrême droite", 
    personality: "Eric Zemmour",
    personalityPhotos: ["/images/personnalites/eric-zemmour.jpg"],
    description: "Vous êtes en faveur d'un État fort qui protège la nation, avec des positions très conservatrices sur le plan social.",
    logo: { light: "/images/logospartis/light/Reconquete.png", dark: "/images/logospartis/dark/Reconquete.png" },
    color: { light: '#102673', dark: '#102673' },
    compass: { x: 80, y: 90 },
    radicalism: 0.90,
    cohesion: 0.95
  }
];

export type Party = typeof PARTIES[number];